### ISSUE TITLE
Build the badge Issuing process

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#18]
**Help wanted: Design, Development, Input**
We're testing out a way to issue badges! In this first prototype we will:

1. The Publisher will manually fill out a form for each paper they're testing badges on
    * form will include: DOI, author emails, author ORCIDs (optional)
2. This will trigger an email to each author with a custom link
3. The custom link will take them to our site and prompt ORCID login
    * The login process will create an ORCID for the author if they do not have one already
4. The custom link brings the author to a form where they can select all roles they contributed for this paper
5. Badges are assigned to that author -- one for each role
    * each badge instance will have: ORCID, DOI & badge (role)

##### Build interface for the publisher (#22)
In the first prototype, Journals will manually enter in the DOI & Author emails in a form.

##### Implement function on Publisher form submission (#23)
* Generate unique link for authors
* Email authors with the link

##### Build interface for the Authors (#24)
The unique link will lead to a form that allows authors to select their roles on a paper (after login via ORCID). This will trigger issuing the badges. Authors can only issue badges to their own ORCID for papers that Publishers have confirmed they authored.

Checklist:

- [x] *[Input, Design, Dev]* #22 Build interface for the publisher
- [x] *[Design]* design the email that goes out to authors 
- [x] *[Dev]* #23 Implement function on Publisher form submission
- [x] *[Design, Dev]* #24 Build interface for the Authors

**Comment by aid29** [comment]
Maybe split out this big issue to 3 steps (issues) as you mentioned above.

**Comment by acabunoc** [comment]
@aid29 - good idea, will do

**Comment by iamjessklein** [comment]
I suspect that you also might need to:

- [ ] design the email that goes out to authors 
- [ ] design the email that goes out to publishers

cc/ @acabunoc

**Comment by acabunoc** [comment]
Thank you @iamjessklein! I'll add those.
